using System.Collections.Generic;

namespace SpiceWizard.Web.Art
{
    /// <summary>
    /// Every sprite in the game, drawn as text with <see cref="Palette"/> letters. Rows in one sprite
    /// must all be the same width. Grey-scale sprites (W/g/G/K) are meant to be tinted at draw time.
    /// Light comes from the top-left: highlights sit up and left, shadows down and right, and most
    /// things carry a 1px outline (K) and a translucent ground shadow (q) so they read cleanly.
    /// </summary>
    public static class Sprites
    {
        public static readonly Dictionary<string, string[]> All = new Dictionary<string, string[]>
        {
            // ---- The wizard (12x20) ------------------------------------------------
            ["wizard0"] = new[]
            {
                "......KK....",
                ".....KpPK...",
                "....KpPPK...",
                "...KppPPK...",
                "..KppPPPPK..",
                ".KYyyyyyYYK.",
                "..KkkkkkK...",
                ".KkkKkkKkK..",
                ".KkkkkkkUK..",
                "..KWWWWWK...",
                "..KWWwWwK...",
                "...KWwwK....",
                ".KPPPPPPvK..",
                "KpPPPPPPPvK.",
                "KpPPYyyYPvK.",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                ".KPPPPPPvK..",
                "..KddKKddK..",
                "..KddK.KddK.",
            },
            ["wizard1"] = new[]
            {
                "......KK....",
                ".....KpPK...",
                "....KpPPK...",
                "...KppPPK...",
                "..KppPPPPK..",
                ".KYyyyyyYYK.",
                "..KkkkkkK...",
                ".KkkKkkKkK..",
                ".KkkkkkkUK..",
                "..KWWWWWK...",
                "..KWWwWwK...",
                "...KWwwK....",
                ".KPPPPPPvK..",
                "KpPPPPPPPvK.",
                "KpPPYyyYPvK.",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                ".KPPPPPPvK..",
                ".KddK..KddK.",
                "KddK....KddK",
            },

            // Idle: same stance, the hat tip flops over to the side.
            ["wizard_idle"] = new[]
            {
                ".......KK...",
                "......KpPK..",
                "....KKpPPK..",
                "...KppPPK...",
                "..KppPPPPK..",
                ".KYyyyyyYYK.",
                "..KkkkkkK...",
                ".KkkKkkKkK..",
                ".KkkkkkkUK..",
                "..KWWWWWK...",
                "..KWWwWwK...",
                "...KWwwK....",
                ".KPPPPPPvK..",
                "KpPPPPPPPvK.",
                "KpPPYyyYPvK.",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                ".KPPPPPPvK..",
                "..KddKKddK..",
                "..KddK.KddK.",
            },
            // Idle: a quiet smoke. Two columns wider than the others so the pipe can poke out past the beard
            // (the actor shifts it left when flipped so the body stays put).
            ["wizard_pipe"] = new[]
            {
                "......KK......",
                ".....KpPK.....",
                "....KpPPK.....",
                "...KppPPK.....",
                "..KppPPPPK....",
                ".KYyyyyyYYK...",
                "..KkkkkkK.....",
                ".KkkKkkKkK....",
                ".KkkkkkkUK....",
                "..KWWWWWKdd...",
                "..KWWwWwK.KBBK",
                "...KWwwK..KbBK",
                ".KPPPPPPvK.KK.",
                "KpPPPPPPPvK...",
                "KpPPYyyYPvK...",
                "KpPPPPPPPvK...",
                "KpPPPPPPPvK...",
                ".KPPPPPPvK....",
                "..KddKKddK....",
                "..KddK.KddK...",
            },
            // Seen from behind (walking into the tower): hat, white hair, plain robe.
            ["wizard_back0"] = new[]
            {
                "......KK....",
                ".....KpPK...",
                "....KpPPK...",
                "...KppPPK...",
                "..KppPPPPK..",
                ".KYyyyyyYYK.",
                "..KWWWWwK...",
                ".KWWWWWwwK..",
                ".KWWWWwwwK..",
                "..KWWWwwK...",
                "..KWWwwwK...",
                "...KWwwK....",
                ".KPPPPPPvK..",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                ".KPPPPPPvK..",
                "..KddKKddK..",
                "..KddK.KddK.",
            },
            ["wizard_back1"] = new[]
            {
                "......KK....",
                ".....KpPK...",
                "....KpPPK...",
                "...KppPPK...",
                "..KppPPPPK..",
                ".KYyyyyyYYK.",
                "..KWWWWwK...",
                ".KWWWWWwwK..",
                ".KWWWWwwwK..",
                "..KWWWwwK...",
                "..KWWwwwK...",
                "...KWwwK....",
                ".KPPPPPPvK..",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                "KpPPPPPPPvK.",
                ".KPPPPPPvK..",
                ".KddK..KddK.",
                "KddK....KddK",
            },

            // ---- Action poses (played over the idle while a panel is open; see WizardActor.Pose) ----
            // Watering: the arm reaches out and tips the bucket, two columns wider on the right.
            ["wizard_water"] = new[]
            {
                "......KK......",
                ".....KpPK.....",
                "....KpPPK.....",
                "...KppPPK.....",
                "..KppPPPPK....",
                ".KYyyyyyYYK...",
                "..KkkkkkK.....",
                ".KkkKkkKkK....",
                ".KkkkkkkUK....",
                "..KWWWWWK.....",
                "..KWWwWwK.....",
                "...KWwwK...KK.",
                ".KPPPPPPvKKbdK",
                "KpPPPPPPPPkKdK",
                "KpPPYyyYPvK.Kc",
                "KpPPPPPPPvK..c",
                "KpPPPPPPPvK...",
                ".KPPPPPPvK....",
                "..KddKKddK....",
                "..KddK.KddK...",
            },
            // Stirring the cauldron: a long ladle raised, then dipped. Both two columns wider on the right.
            ["wizard_stir0"] = new[]
            {
                "......KK......",
                ".....KpPK.....",
                "....KpPPK.....",
                "...KppPPK...KK",
                "..KppPPPPK.KgK",
                ".KYyyyyyYYK.KK",
                "..KkkkkkK...dK",
                ".KkkKkkKkK..dK",
                ".KkkkkkkUK.dK.",
                "..KWWWWWK..dK.",
                "..KWWwWwK.dK..",
                "...KWwwK.KkK..",
                ".KPPPPPPPPkK..",
                "KpPPPPPPPvK...",
                "KpPPYyyYPvK...",
                "KpPPPPPPPvK...",
                "KpPPPPPPPvK...",
                ".KPPPPPPvK....",
                "..KddKKddK....",
                "..KddK.KddK...",
            },
            ["wizard_stir1"] = new[]
            {
                "......KK......",
                ".....KpPK.....",
                "....KpPPK.....",
                "...KppPPK.....",
                "..KppPPPPK....",
                ".KYyyyyyYYK...",
                "..KkkkkkK.....",
                ".KkkKkkKkK....",
                ".KkkkkkkUK....",
                "..KWWWWWK.....",
                "..KWWwWwK.....",
                "...KWwwK......",
                ".KPPPPPPvK.KKK",
                "KpPPPPPPPPkddK",
                "KpPPYyyYPvKKgK",
                "KpPPPPPPPvK.KK",
                "KpPPPPPPPvK...",
                ".KPPPPPPvK....",
                "..KddKKddK....",
                "..KddK.KddK...",
            },
            // Grinding: both hands on a pestle held down in front; the actor bobs it up and down.
            ["wizard_grind"] = new[]
            {
                "......KK....",
                ".....KpPK...",
                "....KpPPK...",
                "...KppPPK...",
                "..KppPPPPK..",
                ".KYyyyyyYYK.",
                "..KkkkkkK...",
                ".KkkKkkKkK..",
                ".KkkkkkkUK..",
                "..KWWWWWK...",
                "..KWWwWwK.KK",
                "...KWwwK..Kd",
                ".KPPPPPPvKKd",
                "KpPPPPPPPkKd",
                "KpPPYyyYPkKd",
                "KpPPPPPPPvKK",
                "KpPPPPPPPvK.",
                ".KPPPPPPvK..",
                "..KddKKddK..",
                "..KddK.KddK.",
            },
            // Cheering: both arms straight up. One column wider on each side, so the actor shifts it left by one.
            ["wizard_cheer"] = new[]
            {
                ".......KK.....",
                "KK....KpPK..KK",
                "KkK..KpPPK.KkK",
                "KPK.KppPPK.KPK",
                "KPKKppPPPPKKPK",
                "KPKYyyyyyYYKPK",
                "KPKKkkkkkK.KPK",
                "KPKkkKkkKkK.PK",
                "KPKkkkkkkUK.PK",
                "KPKKWWWWWK.KPK",
                "KPKKWWwWwK.KPK",
                "KPK.KWwwK..KPK",
                "KPPPPPPPPvPPvK",
                "KKpPPPPPPPvKKK",
                ".KpPPYyyYPvK..",
                ".KpPPPPPPPvK..",
                ".KpPPPPPPPvK..",
                "..KPPPPPPvK...",
                "...KddKKddK...",
                "...KddK.KddK..",
            },

            // ---- Garden (24x16 plots, 16x16 plants) --------------------------------
            // A raised bed: light top board, dark front board, furrowed soil.
            ["plot"] = new[]
            {
                "........................",
                ".KKKKKKKKKKKKKKKKKKKKKK.",
                "KNbbbbbbbbbbbbbbbbbbbbBK",
                "KbssssssssssssssssssssBK",
                "KbsSSSSSSSSSSSSSSSSSSsBK",
                "KbssssssssssssssssssssBK",
                "KbsSSSSSSSSSSSSSSSSSSsBK",
                "KbssssssssssssssssssssBK",
                "KbsSSSSSSSSSSSSSSSSSSsBK",
                "KbssssssssssssssssssssBK",
                "KbsSSSSSSSSSSSSSSSSSSsBK",
                "KbssssssssssssssssssssBK",
                "KBBBBBBBBBBBBBBBBBBBBBBK",
                "KddddddddddddddddddddddK",
                ".KKKKKKKKKKKKKKKKKKKKKK.",
                "qqqqqqqqqqqqqqqqqqqqqqqq",
            },
            ["plot_wet"] = new[]
            {
                "........................",
                ".KKKKKKKKKKKKKKKKKKKKKK.",
                "KNbbbbbbbbbbbbbbbbbbbbBK",
                "KbSSSSSSSSSSSSSSSSSSSSBK",
                "KbS00000000000000000SSBK",
                "KbSSSSSSSSSSSSSSSSSSSSBK",
                "KbS00000000000000000SSBK",
                "KbSSSSSSSSSSSSSSSSSSSSBK",
                "KbS00000000000000000SSBK",
                "KbSSSSSSSSSSSSSSSSSSSSBK",
                "KbS00000000000000000SSBK",
                "KbSSSSSSSSSSSSSSSSSSSSBK",
                "KBBBBBBBBBBBBBBBBBBBBBBK",
                "KddddddddddddddddddddddK",
                ".KKKKKKKKKKKKKKKKKKKKKK.",
                "qqqqqqqqqqqqqqqqqqqqqqqq",
            },
            // Not yet dug: a weedy patch of bare earth with a couple of stones.
            ["plot_locked"] = new[]
            {
                "....L.......L.....L.....",
                "...LlL.....LlL...LlL....",
                "..KssLKKKKKsLsKKKKLsK...",
                ".KsssssssssssssssssssK..",
                ".KssKKKsssssssssKKKsssK.",
                ".KsKmmMKsssLssssKmMKssK.",
                ".KsKMMMKssLlLsssKMMKssK.",
                ".KssKKKssssLssssKKKsssK.",
                ".KssssssssLsssssssssssK.",
                ".KsssLsssssssssLsssssK..",
                ".KssLlLsssssssLlLsssssK.",
                ".KsssLssssssssLssssssK..",
                "..KsssssssssssssssssssK.",
                "...KKKKKKKKKKKKKKKKKKK..",
                "........................",
                "........................",
            },
            ["seed"] = new[]
            {
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                ".......KK.......",
                "......KNbK......",
                "......KbBK......",
                ".......KK.......",
                "................",
                "................",
                "................",
            },
            ["sprout"] = new[]
            {
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                ".......KK.......",
                "......KlLK......",
                "....KK.KLK.KK...",
                "...KlLK.L.KLLK..",
                "....KLK.L.KLK...",
                ".....K..L..K....",
                ".......KLK......",
                ".......KLK......",
                "................",
            },
            ["bud"] = new[]
            {
                "................",
                "................",
                "................",
                ".......KK.......",
                "......KlLK......",
                ".....KllLLK.....",
                "....KKlLLLKK....",
                "...KlLK.L.KLLK..",
                "..KlLK..L..KLDK.",
                "...KLK..L..KLK..",
                "....K..iL..K....",
                ".....KlLLLK.....",
                "......KLDK......",
                ".......KLK......",
                ".......KLK......",
                "................",
            },
            // Bell peppers look like bronze bells hanging from the bush.
            ["mature_bell"] = new[]
            {
                ".......KK.......",
                "......KlLK......",
                ".....KllLLK.....",
                "....KlLK.LLK....",
                "...KlLK.L.KLK...",
                "..KlLK.lLl.KLK..",
                ".KLK.KlLLLK.KLK.",
                ".KYYK..L..KYYK..",
                "KZyYYK.L.KZyYYK.",
                "KZyYYK.L.KZyYYK.",
                "KZyYYK.L.KZyYYK.",
                "KYYYYK.L.KYYYYK.",
                "KOOOOK.L.KOOOOK.",
                ".KKKK..L..KKKK..",
                "..KK...L...KK...",
                ".......L........",
            },
            // Banana peppers are, of course, bananas.
            ["mature_banana"] = new[]
            {
                ".......KK.......",
                "......KlLK......",
                ".....KllLLK.....",
                "....KlLK.LLK....",
                "...KlLK.L.KLK...",
                "..KlLK.lLl.KLK..",
                ".KLK.KlLLLK.KLK.",
                "..KdK..L..KdK...",
                "..KZyK.L.KZyK...",
                "..KZyyK.LKZyyK..",
                "...KyyyKLKyyyK..",
                "....KyyyKKyyyK..",
                "....KYyyK.KyyYK.",
                ".....KYYK..KYYK.",
                "......KK....KK..",
                ".......L........",
            },
            // Bonnet peppers are frilly bonnet hats with a ribbon bow.
            ["mature_bonnet"] = new[]
            {
                ".......KK.......",
                "......KlLK......",
                ".....KllLLK.....",
                "....KlLK.LLK....",
                "...KlLK.L.KLK...",
                "..KlLK.lLl.KLK..",
                ".KLK.KlLLLK.KLK.",
                "....KKKKKKKK....",
                "...KoZooooOOK...",
                "..KoooooooooOK..",
                "..KOooooooooOKi.",
                ".KWwWwWwWwWwWKiK",
                "..KwwwwwwwwwwKi.",
                "...KKKKKKKKKK...",
                ".......L........",
                ".......L........",
            },
            // Ghost peppers: a withered grey plant; the ghost itself floats above (see "ghost").
            ["mature_ghost"] = new[]
            {
                "................",
                "................",
                "................",
                "................",
                "................",
                ".......KK.......",
                "......KgGK......",
                ".....KgK.KK.....",
                "....KgK...KGK...",
                "...KGK.KgK.KGK..",
                "..KgK.KGKGK.KGK.",
                "...K..KgKGK..K..",
                ".......KGK......",
                "........G.......",
                "........G.......",
                "........G.......",
            },
            // The ghost of a chili pepper: pale, eyed, curling pod with a wispy tail.
            ["ghost"] = new[]
            {
                "..LL......",
                "...L......",
                "..tttt....",
                ".ttttttT..",
                ".tKttKtT..",
                ".ttttttT..",
                ".tttttttT.",
                "..ttttTT..",
                "...ttTtT..",
                "....tT.t..",
            },

            // ---- Stations --------------------------------------------------------------
            // Well of stacked stone courses (offset joints, dark mortar) with a shingled roof, two posts and a bucket on a rope.
            ["well"] = new[]
            {
                "......KKKKKKKK......",
                ".....KbbbbbbbbK.....",
                "....KbBbbBbbBbbK....",
                "...KbBbbBbbBbbBbK...",
                "..KBBBBBBBBBBBBBBK..",
                "..KKKKKKKKKKKKKKKK..",
                "...Kd....K......dK..",
                "...Kd....K......dK..",
                "...Kd...KbbK....dK..",
                "...Kd...KBBK....dK..",
                "...Kd....KK.....dK..",
                "..KKKKKKKKKKKKKKKK..",
                ".KfffKKKKKKKKKKfffK.",
                ".KffKnnnnnnnnnnKffK.",
                ".KffffffffffffffffK.",
                ".KfmmmMfmmmMfmmmMfK.",
                ".KmmmMMmmmMMmmmMMmK.",
                ".KMMMMMMMMMMMMMMMMK.",
                ".KfmMfmmmMfmmmMfmmK.",
                ".KmMMmmmMMmmmMMmmmK.",
                ".KMMMMMMMMMMMMMMMMK.",
                ".KfmmmMfmmmMfmmmMfK.",
                ".KmmmMMmmmMMmmmMMmK.",
                ".KMMMMMMMMMMMMMMMMK.",
                "..KKKKKKKKKKKKKKKK..",
                "qqqqqqqqqqqqqqqqqqqq",
            },
            ["bucket"] = new[]
            {
                ".KKKKKK.",
                "Kd....dK",
                "KNbbbbBK",
                "KBbbbbBK",
                "KBbbbbBK",
                "KBBbbBBK",
                ".KBBBBK.",
                "..KKKK..",
            },
            // Notice board: a sheet of paper pinned to a plank frame on two posts.
            ["board"] = new[]
            {
                ".KKKKKKKKKKKKKKKKKK.",
                "KNbbbbbbbbbbbbbbbbbK",
                "KbKKKKKKKKKKKKKKKKBK",
                "KbKWWWWWWWWWWWWWWKBK",
                "KbKWKKKWWWWKKKKWWKBK",
                "KbKWWWWWWWWWWWWWWKBK",
                "KbKWKKKKKKWKKKWWWKBK",
                "KbKWWWWWWWWWWWWWWKBK",
                "KbKWKKKKWWKKKKKWWKBK",
                "KbKWWWWWWWWWWWWWWKBK",
                "KbKWKKKWWKKKKKKWWKBK",
                "KbKWWWWWWWWWWWWWWKBK",
                "KbKwwwwwwwwwwwwwwKBK",
                "KbKKKKKKKKKKKKKKKKBK",
                "KddddddddddddddddddK",
                ".KKKKKKKKKKKKKKKKKK.",
                ".....KdK....KdK.....",
                ".....KdK....KdK.....",
                ".....KdK....KdK.....",
                ".....KdK....KdK.....",
                ".....KdK....KdK.....",
                ".....KdK....KdK.....",
                "....KKKK...KKKK.....",
                "qqqqqqqqqqqqqqqqqqqq",
            },
            // The merchant's cart: striped awning, goods on the counter, two spoked wheels.
            ["cart"] = new[]
            {
                "........KKKKKKKKKKKKKKKKKKKK........",
                ".......KrrrrrrrrrrrrrrrrrrrrK.......",
                "......KrrWWrrWWrrWWrrWWrrWWrrK......",
                ".....KrrrWWrrWWrrWWrrWWrrWWrrrK.....",
                ".....KRRRRRRRRRRRRRRRRRRRRRRRRK.....",
                "......Kd.....................dK.....",
                "......Kd.....................dK.....",
                "......Kd.yy..oo..ee..bb..pp..dK.....",
                "......Kd.YY..OO..EE..BB..PP..dK.....",
                "......KKKKKKKKKKKKKKKKKKKKKKKKK.....",
                "......KNbbbbbbbbbbbbbbbbbbbbbbK.....",
                "......KbBbbBbbBbbBbbBbbBbbBbbBK.....",
                "......KbBBBBBBBBBBBBBBBBBBBBBBK.....",
                "......KbBbbBbbBbbBbbBbbBbbBbbBK.....",
                "......KdBBBBBBBBBBBBBBBBBBBBBdK.....",
                "..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
                "..KddddddddddddddddddddddddddddddK..",
                ".....KKKK................KKKK.......",
                "....KdBBdK..............KdBBdK......",
                "....KBdKdBK.............KBdKdBK.....",
                "....KdBBdK..............KdBBdK......",
                ".....KKKK................KKKK.......",
            },
            ["merchant"] = new[]
            {
                "....KKKK....",
                "..KKeeeeKK..",
                ".KeeEeeeeeK.",
                ".KeeeeeeEeK.",
                ".KYyyyyyyYK.",
                "..KkkkkkkK..",
                "..KkKkkKkK..",
                "..KkkkkkUK..",
                "...KkkkkK...",
                "..KBBBBBBK..",
                ".KbBBBBBBBK.",
                ".KbBBBBBBdK.",
                ".KbBBBBBBdK.",
                ".KbBddddBdK.",
                "..KBBBBBBK..",
                "..KddKKddK..",
                "..KddK.KddK.",
                "............",
            },
            // A bottle that pops out of the cauldron and arcs over to the pantry (tinted with the sauce).
            ["bottle"] = new[]
            {
                "..KK..",
                "..KK..",
                ".KggK.",
                "KWWWgK",
                "KWWWgK",
                "KWWWgK",
                "KWWggK",
                ".KggK.",
                "..KK..",
            },
            ["crate"] = new[]
            {
                ".KKKKKKKKKKKKKKKK.",
                "KNNNNNNNNNNNNNNNBK",
                "KbddddddddddddddBK",
                "KbdbbbbbbbbbbbbdBK",
                "KbdbBBBBBBBBBBbdBK",
                "KbdbBBBBBBBBBBbdBK",
                "KbdbbbbbbbbbbbbdBK",
                "KbddddddddddddddBK",
                "KbdbbbbbbbbbbbbdBK",
                "KbdbBBBBBBBBBBbdBK",
                "KbdbbbbbbbbbbbbdBK",
                "KBddddddddddddddBK",
                ".KKKKKKKKKKKKKKKK.",
                "qqqqqqqqqqqqqqqqqq",
            },
            ["crate_full"] = new[]
            {
                ".KKKKKKKKKKKKKKKK.",
                "KNNNNNNNNNNNNNNNBK",
                "KbdKKdKKdKKdKKddBK",
                "KbdrrdyydoodppddBK",
                "KbdrrdyydoodppddBK",
                "KbdRRdYYdOOdPPddBK",
                "KbddddddddddddddBK",
                "KbddddddddddddddBK",
                "KbdbbbbbbbbbbbbdBK",
                "KbdbBBBBBBBBBBbdBK",
                "KbdbbbbbbbbbbbbdBK",
                "KBddddddddddddddBK",
                ".KKKKKKKKKKKKKKKK.",
                "qqqqqqqqqqqqqqqqqq",
            },
            // Round-bellied iron cauldron standing on four legs; the green brew shows at the rim,
            // bubbles are drawn on top and the fire sprite goes underneath, between the legs.
            ["cauldron"] = new[]
            {
                "........................",
                "........................",
                "........................",
                "....KKKKKKKKKKKKKKKK....",
                "..KKXXXXXXXXXXXXXXXXKK..",
                ".KXXKlLLLLLLLLLLLLLKXXK.",
                ".KXxKKKKKKKKKKKKKKKKxxK.",
                ".KXxxxxxxxxxxxxxxxxxxxK.",
                ".KXxxxxxxxxxxxxxxxxxxxK.",
                ".KXxxxxxxxxxxxxxxxxxxxK.",
                ".KXxxxxxxxxxxxxxxxxxxxK.",
                ".KXxxxxxxxxxxxxxxxxxxxK.",
                "..KXxxxxxxxxxxxxxxxxxK..",
                "...KXxxxxxxxxxxxxxxxK...",
                "....KKxxxxxxxxxxxxKK....",
                "......KKKKKKKKKKKK......",
                ".....KxK........KxK.....",
                ".....KxK........KxK.....",
                ".....KxK........KxK.....",
                ".....KxK........KxK.....",
                "....KKKKK......KKKKK....",
                "........................",
            },
            // Log fire, 2px wider than the cauldron on each side: the logs lie on the ground under the
            // legs, the middle flames burn between them and the outer tongues lick up the belly.
            ["fire0"] = new[]
            {
                "............................",
                "..o.........................",
                ".oyo......................o.",
                ".oyo.........o...........oyo",
                "oyZyo.......oyo.....o..oyZyo",
                "oyZyo......oyZyo...oyo.oyZyo",
                "royZyorrrroyZZZZyorrrroyZyor",
                "rroyorrrrrroyZZyorrrrrroyorr",
                ".rrrrrrrrrroooooooorrrrrrrr.",
                "..KdBdBdBdBdBdBdBdBdBdBdK...",
            },
            ["fire1"] = new[]
            {
                "............................",
                ".........................o..",
                ".o......................oyo.",
                "oyo..........o..........oyo.",
                "oyZyo.......oyo....o...oyZyo",
                "oyZyo......oyZyo..oyo..oyZyo",
                "royZyorrrroyZZZZyorrrroyZyor",
                "rroyorrrrrroyZZyorrrrrroyorr",
                ".rrrrrrrrrroooooooorrrrrrrr.",
                "..KdBdBdBdBdBdBdBdBdBdBdK...",
            },
            ["bubbles0"] = new[]
            {
                "........................",
                "........................",
                ".........W..............",
                "......W.................",
                "............W....W......",
                "........W...............",
                "........................",
                "........................",
            },
            ["bubbles1"] = new[]
            {
                "........................",
                "..........W.............",
                "........................",
                "...............W........",
                "......W.................",
                "..........W......W......",
                "........................",
                "........................",
            },
            ["bubbles2"] = new[]
            {
                ".............W..........",
                "........................",
                ".......W................",
                "..................W.....",
                "........................",
                ".....W.......W..........",
                "........................",
                "........................",
            },
            // Shelf on the tower wall: the board, two brackets, and its shadow on the stone.
            ["shelf"] = new[]
            {
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "............................................",
                "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
                "KNbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK",
                "KBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBK",
                "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
                ".KdKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKdK.",
                "..KdK..................................KdK..",
            },
            // Glass jar: outline, lid and a highlight; the wall shows through the glass.
            ["jar"] = new[]
            {
                "..KKKKKK..",
                "..KNbbBK..",
                ".KKddddKK.",
                ".KWQQQQQK.",
                ".KWQQQQQK.",
                ".KWQQQQQK.",
                ".KWQQQQQK.",
                ".KWQQQQQK.",
                ".KWQQQQQK.",
                ".KWQQQQQK.",
                ".KWQQQQQK.",
                ".KWQQQQQK.",
                ".KQQQQQQK.",
                "..KKKKKK..",
            },
            // Jar contents, tinted per species and drawn under the jar.
            ["jar_fill"] = new[]
            {
                "..........",
                "..........",
                "..........",
                "..........",
                "..........",
                "..WWWWWW..",
                "..WWWWWg..",
                "..WWWWWg..",
                "..WWWWWg..",
                "..WWWWWg..",
                "..WWWWWg..",
                "..WWWWWg..",
                "..gggggg..",
                "..........",
            },
            ["jar_lock"] = new[]
            {
                "..........",
                "..........",
                "...KKKK...",
                "..KGggGK..",
                "..KG..GK..",
                ".KKKKKKKK.",
                ".KZyyyyYK.",
                ".KZyKKyYK.",
                ".KZyKKyYK.",
                ".KZyyKyYK.",
                ".KYYYYYYK.",
                ".KKKKKKKK.",
                "..........",
                "..........",
            },
            // Stone mortar with a wooden pestle resting in it.
            ["mortar"] = new[]
            {
                "..........KK..",
                ".........KNbK.",
                "........KbBK..",
                ".KKKKKKKKBBK..",
                "KffffffffKKfK.",
                "KfmmmmmmmmmmMK",
                "KfmmmmmmmmmmMK",
                ".KfmmmmmmmmMK.",
                "..KfmmmmmmMK..",
                "...KKmmmmKK...",
                "..KMMMMMMMMK..",
                "..KKKKKKKKKK..",
            },
            // Cut log seen a little from above: rings on top, bark down the side.
            ["stump"] = new[]
            {
                "...KKKKKKKKKKKK...",
                ".KKbbbbbbbbbbbbKK.",
                "KbbbNNNNNNNNNNbbbK",
                "KbbNbbbbbbbbbbNbbK",
                "KbbbNNNNNNNNNNbbbK",
                ".KKddddddddddddKK.",
                ".KBBdBBdBBdBBdBBK.",
                ".KBBdBBdBBdBBdBBK.",
                ".KddddddddddddddK.",
                "..KKKKKKKKKKKKKK..",
            },
            // Pantry chest: banded lid, iron lock, little feet.
            ["pantry"] = new[]
            {
                ".KKKKKKKKKKKKKKKK.",
                "KNbbbbbbbbbbbbbbBK",
                "KbBBBBBBBBBBBBBBdK",
                "KbBYYBBBBBBBBYYBdK",
                "KKKKKKKKKKKKKKKKKK",
                "KbbYYbbbbbbbbYYbBK",
                "KbbYYbbbbKKbbYYbBK",
                "KbbYYbbbbKKbbYYbBK",
                "KbbYYbbbbbbbbYYbBK",
                "KBBYYBBBBBBBBYYBdK",
                "KddddddddddddddddK",
                ".KKKKKKKKKKKKKKKK.",
                "..KK..........KK..",
                "qqqqqqqqqqqqqqqqqq",
            },
            // Arched oak door set into the tower wall, with two iron bands and a knob.
            ["door"] = new[]
            {
                "....KKKKKK....",
                "..KKMMMMMMKK..",
                ".KMMKKKKKKMMK.",
                ".KMKbbbbbbKMK.",
                "KMKbBBBBBBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKYYYYYYYYKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBYBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKYYYYYYYYKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKbBdBBdBbKMK",
                "KMKddddddddKMK",
                "KMKKKKKKKKKKMK",
                "KKKKKKKKKKKKKK",
            },
            // The same doorway with the leaf swung out to the left (seen edge-on, 3px wide) and the
            // interior left transparent so the renderer can light it and clip the wizard inside.
            ["door_open"] = new[]
            {
                ".......KKKKKK....",
                ".....KKMMMMMMKK..",
                "KK..KMMKKKKKKMMK.",
                "KbK.KMK......KMK.",
                "KBKKMK........KMK",
                "KbKKMK........KMK",
                "KBKKMK........KMK",
                "KYKKMK........KMK",
                "KbKKMK........KMK",
                "KBKKMK........KMK",
                "KbKKMK........KMK",
                "KBKKMK........KMK",
                "KbKKMK........KMK",
                "KBKKMK........KMK",
                "KbKKMK........KMK",
                "KBKKMK........KMK",
                "KbKKMK........KMK",
                "KBKKMK........KMK",
                "KYKKMK........KMK",
                "KbKKMK........KMK",
                "KBKKMK........KMK",
                "KbKKMK........KMK",
                "KBKKMK........KMK",
                "KdKKMK........KMK",
                "KKKKMKKKKKKKKKKMK",
                "...KKKKKKKKKKKKKK",
            },
            ["window"] = new[]
            {
                "..KKKK..",
                ".KjjccK.",
                "KjjcKccK",
                "KjccKccK",
                "KKKKKKKK",
                "KcccKccK",
                "KcccKCCK",
                ".KccKCK.",
                ".KKKKKK.",
                "KMMMMMMK",
            },
            ["window_lit"] = new[]
            {
                "..KKKK..",
                ".KZZyyK.",
                "KZZyKyyK",
                "KZyyKyyK",
                "KKKKKKKK",
                "KyyyKyyK",
                "KyyyKYYK",
                ".KyyKYK.",
                ".KKKKKK.",
                "KMMMMMMK",
            },
            ["roof"] = new[]
            {
                ".........................KK.........................",
                "........................KyZK........................",
                "........................KYyK........................",
                ".........................KK.........................",
                "........................KppK........................",
                ".......................KppvvK.......................",
                ".....................KppPPvvvvK.....................",
                "....................KpppPPPpvvvK....................",
                "..................KppPPPvPPPvPvvvK..................",
                ".................KppPpPPPpPPPpPvvvK.................",
                "...............KppvPPPvPPPvPPPvPPvvvK...............",
                "..............KppPPpPPPpPPPpPPPpPPvvvK..............",
                "............KppPvPPPvPPPvPPPvPPPvPPPvvvK............",
                "...........KppPPPpPPPpPPPpPPPpPPPpPPPvvvK...........",
                ".........KppPPvPPPvPPPvPPPvPPPvPPPvPPPvvvvK.........",
                "........KpppPPPpPPPpPPPpPPPpPPPpPPPpPPPpvvvK........",
                "......KppPPPvPPPvPPPvPPPvPPPvPPPvPPPvPPPvPvvvK......",
                ".....KppPpPPPpPPPpPPPpPPPpPPPpPPPpPPPpPPPpPvvvK.....",
                "...KppvPPPvPPPvPPPvPPPvPPPvPPPvPPPvPPPvPPPvPPvvvK...",
                "..KppPPpPPPpPPPpPPPpPPPpPPPpPPPpPPPpPPPpPPPpPPvvvK..",
                "KppPvPPPvPPPvPPPvPPPvPPPvPPPvPPPvPPPvPPPvPPPvPPPvvvK",
                "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
                "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
                "..qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq..",
            },
            ["sun"] = new[]
            {
                "....yy....",
                ".y.yZZy.y.",
                "..yZZZZy..",
                ".yZZZZZZy.",
                "yZZZZZZZZy",
                "yZZZZZZZZy",
                ".yZZZZZZy.",
                "..yZZZZy..",
                ".y.yZZy.y.",
                "....yy....",
            },
            ["moon"] = new[]
            {
                "...wwww...",
                "..wWWWww..",
                ".wWWw.....",
                ".wWw......",
                "wWWw......",
                "wWWw......",
                ".wWw......",
                ".wWWw.....",
                "..wWWWww..",
                "...wwww...",
            },
            ["cloud"] = new[]
            {
                "......WWWW..........",
                "...WWWWWWWWW..WWW...",
                ".WWWWWWWWWWWWWWWWWW.",
                "WWWWWWWWWWWWWWWWWWWW",
                "WWWWWWWWWWWWWWWWWWWW",
                ".WzzWWWWWzzWWWWWzzW.",
                "..zzzzzzzzzzzzzzzz..",
                "....................",
            },
            ["cloud_big"] = new[]
            {
                "...............WWWWW............",
                "............WWWWWWWWWWW.........",
                "...........WWWWWWWWWWWWW........",
                ".....WWWWWWWWWWWWWWWWWWWWWW.....",
                "...WWWWWWWWWWWWWWWWWWWWWWWWWWW..",
                "..WWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
                "..WWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
                ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
                "..WWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
                "..zzzzzzzzzzzzzzzzzzzzzzzzzzzzz.",
                "...zzzzzzzzzzzzzzzzzzzzzzzzzzz..",
                ".....zzzzzzzzzzz...zzzzzzzz.....",
            },
            ["tree"] = new[]
            {
                "......KKKK......",
                "....KKllLLKK....",
                "...KlllLLLLLK...",
                "..KllLLLLLLLLK..",
                "..KlLLLLLLLLDK..",
                ".KllLLLLLLLLDDK.",
                ".KlLLLLLLLLLDDK.",
                ".KlLLLLLLLDDDDK.",
                ".KLLLLLLLLDDDDK.",
                "..KLLLLLDDDDDK..",
                "..KLLLLDDDDDDK..",
                "...KLLDDDDDDK...",
                "....KKDDDDKK....",
                "......KddK......",
                "......KdBK......",
                "......KdBK......",
                "......KdBK......",
                "......KdBK......",
                ".....KKdBKK.....",
                "....KddddBBK....",
                "....KKKKKKKK....",
                "..qqqqqqqqqqqq..",
                "................",
                "................",
            },
            ["tree_big"] = new[]
            {
                "........................",
                ".......KKKKKKKKKK.......",
                ".....KKlllllllLLLKK.....",
                "....KKllllllLLLLLLKK....",
                "...KlllllllLLLLLLLLLK...",
                "..KKlllllLDLLLlLLLLLKK..",
                "..KlllllLLLLLLLDLLLLLK..",
                ".KlllllDLLLLLLLLLLLLLLK.",
                ".KlllLLLLLLLLLLLLLLLDDK.",
                ".KllLLLLLLLlLLLLLLLDDDK.",
                ".KLLLLLLLLLLDLLLLLDDDDK.",
                ".KLLLLLLLLLLLLLLDDDDDDK.",
                ".KLLLLLLLLLLLLLDLDDDDDK.",
                ".KLLLLDLLLLLLDDDDDDDDDK.",
                ".KLLLLLLLLLLDDDDDDDDDDK.",
                "..KLLLLLLLDDDDDDDDDDDK..",
                "..KKLLLLLDDDDDDLDDDDKK..",
                "...KLLLDDDDDDDDDDDDDK...",
                "....KKDDDDDDDDDDDDKK....",
                ".....KKDDDDDDDDDDKK.....",
                ".......KKKddBBKKK.......",
                ".........KddBBK.........",
                ".........KddBBK.........",
                ".........KddBBK.........",
                ".........KddBBK.........",
                ".........KddBBK.........",
                ".........KddBBK.........",
                ".........KddBBK.........",
                ".........KddBBK.........",
                ".......KKddddBBBKK......",
                "......KddddBBBBBBK......",
                "......KKKKKKKKKKKK......",
                "....qqqqqqqqqqqqqqqq....",
                "........................",
            },
            ["bush"] = new[]
            {
                "...KKKKK....",
                ".KKllLLLKK..",
                "KllLLLLLLLK.",
                "KlLLLLLLDDK.",
                "KLLLLLDDDDDK",
                ".KLLDDDDDDK.",
                "..KKKKKKKK..",
                ".qqqqqqqqqq.",
            },
            // Meadow dressing.
            ["flower_pink"] = new[]
            {
                ".i..",
                "iWi.",
                ".iL.",
                "..L.",
            },
            ["flower_yellow"] = new[]
            {
                ".y..",
                "yZy.",
                ".yL.",
                "..L.",
            },
            ["flower_white"] = new[]
            {
                ".W..",
                "WyW.",
                ".WL.",
                "..L.",
            },
            ["rock"] = new[]
            {
                "..KKKK..",
                ".KfmmMK.",
                "KfmmmMMK",
                "KMMMMMMK",
                ".KKKKKK.",
            },
            // Fence bays: a post at the left and two rails running to the right edge, so they tile
            // horizontally. The variants are mixed along the run so the boards do not repeat, and
            // "fence_post" closes the far end.
            ["fence"] = new[]
            {
                "KNK.........",
                "KbK.........",
                "KbKKKKKKKKKK",
                "KbNbbbbbbbbb",
                "KbKKKKKKKKKK",
                "KbK.........",
                "KbKKKKKKKKKK",
                "KbNbbbbbbbbb",
                "KBKKKKKKKKKK",
                "KKK.........",
            },
            // A knot in the top rail and a nail head where the lower rail meets the post.
            ["fence_b"] = new[]
            {
                "KNK.........",
                "KbK.........",
                "KbKKKKKKKKKK",
                "KbNbbbBdBbbb",
                "KbKKKKKKKKKK",
                "KbK.........",
                "KbKKKKKKKKKK",
                "KbNdbbbbbbbb",
                "KBKKKKKKKKKK",
                "KKK.........",
            },
            // A weathered post with a split top, and the lower rail sagging a pixel toward the next post.
            ["fence_c"] = new[]
            {
                "KNKK........",
                "KbKd........",
                "KbKKKKKKKKKK",
                "KbNbbbbbbbbb",
                "KbKKKKKKKKKK",
                "KbK.........",
                "KbKKKKKKKK..",
                "KbNbbbbbbKKK",
                "KBKKKKKKKbbb",
                "KKK.....KKKK",
            },
            // A shorter, lighter picket with a crack in the top rail and a tuft of grass at its foot.
            ["fence_d"] = new[]
            {
                "............",
                "KNK.........",
                "KbKKKKKKKKKK",
                "KbNbbbbbKbbb",
                "KbKKKKKKKKKK",
                "KbK.........",
                "KbKKKKKKKKKK",
                "KbNbbbbbbbbb",
                "KBKKKKKKKKKK",
                "KKK..u......",
            },
            // The end post that closes the run.
            ["fence_post"] = new[]
            {
                "KNK",
                "KbK",
                "KbK",
                "KbK",
                "KbK",
                "KbK",
                "KbK",
                "KbK",
                "KBK",
                "KKK",
            },
            ["townsfolk0"] = new[]
            {
                "..KKKKKK..",
                ".KrrrrrrK.",
                ".KRrrrrRK.",
                "..KkkkkkK.",
                "..KkKkKkK.",
                "..KkkkkUK.",
                "...KkkkK..",
                "..KcccccK.",
                ".KcccccCCK",
                ".KcccccCCK",
                ".KcccccCCK",
                "..KCCCCCK.",
                "..KddKddK.",
                "..KddKddK.",
                "..KKK.KKK.",
                "..........",
            },
            ["townsfolk1"] = new[]
            {
                "..KKKKKK..",
                ".KZyyyyYK.",
                ".KyyyyYYK.",
                "..KkkkkkK.",
                "..KkKkKkK.",
                "..KkkkkUK.",
                "...KkkkK..",
                "..KeeeeeK.",
                ".KeeeeeEEK",
                ".KeeeeeEEK",
                ".KeeeeeEEK",
                ".KeeeeeEEK",
                "..KEEEEEK.",
                "..KddKddK.",
                "..KKK.KKK.",
                "..........",
            },
            ["townsfolk2"] = new[]
            {
                "..KKKKKK..",
                ".KdBBBBdK.",
                ".KddBBddK.",
                "..KkkkkkK.",
                "..KkKkKkK.",
                "..KkkkkUK.",
                "...KkkkK..",
                "..KoooooK.",
                ".KoooooOOK",
                ".KoooooOOK",
                ".KoooooOOK",
                "..KbbbbbK.",
                "..KddKddK.",
                "..KddKddK.",
                "..KKK.KKK.",
                "..........",
            },

            // ---- Cats (grey-scale: W coat, g markings, K outline; tinted per cat, eyes drawn on top) ----
            ["cat_walk0"] = new[]
            {
                "..KK......K..K..",
                ".KWWK....KWKKWK.",
                "KWWK.....KWWWWK.",
                "KWK......KWWWWWK",
                "KWK....KKKWWWWK.",
                ".KKKKWWWWWWWWWK.",
                "...KWWgWWgWWWK..",
                "...KWWWWWWWWWK..",
                "...KWKKKKKKKWK..",
                "...KWK....KWK...",
                "...KKK....KKK...",
            },
            ["cat_walk1"] = new[]
            {
                "..KK......K..K..",
                ".KWWK....KWKKWK.",
                "KWWK.....KWWWWK.",
                "KWK......KWWWWWK",
                "KWK....KKKWWWWK.",
                ".KKKKWWWWWWWWWK.",
                "...KWWgWWgWWWK..",
                "...KWWWWWWWWWK..",
                "...KKKWKKKWKKK..",
                ".....KWK.KWK....",
                ".....KKK.KKK....",
            },
            ["cat_sit"] = new[]
            {
                ".K...K.....",
                "KWK.KWK....",
                "KWWWWWK....",
                "KWWWWWK....",
                "KWWgWWK....",
                ".KWWWK.....",
                ".KWWWWK....",
                "KWWWWWWK...",
                "KWgWWgWWK..",
                "KWWWWWWWKK.",
                "KWKKKKKWKWK",
                "KKK...KKKKK",
            },
            ["cat_loaf"] = new[]
            {
                ".K.K........",
                "KWKWK.......",
                "KWWWWKKKKKK.",
                "KWWWWWWgWWWK",
                "KWgWWWWWWWWK",
                ".KWWWWWWWWWK",
                ".KKKKKKKKKK.",
            },
            ["cat_sleep"] = new[]
            {
                "....KKKKK....",
                ".K.KWWWWWWK..",
                "KWKWWWWWWWWK.",
                "KWWWWWWWWWWWK",
                "KWGWWWWWWWWWK",
                ".KWWWKKKKKKWK",
                ".KWWKWWWWWWKK",
                "..KKKKKKKKKK.",
            },
            ["cat_roll0"] = new[]
            {
                ".....K.K...K.K..",
                "....KWK...KWK...",
                ".KK.KWWWKKKWWWK.",
                "KWWKKWWWWWWWWWKK",
                "KWWWWWWWWWWWWWWK",
                "KWWWWWWggggWWWWK",
                ".KWWWWWWWWWWWKK.",
                "..KKKKKKKKKKK...",
            },
            ["cat_roll1"] = new[]
            {
                "...K.K...K.K....",
                "..KWK...KWK.....",
                ".KKKWWWKKKWWWKK.",
                "KWWKWWWWWWWWWWWK",
                "KWWWWWWWWWWWWWWK",
                "KWWWWWWggggWWWWK",
                ".KWWWWWWWWWWWKK.",
                "..KKKKKKKKKKK...",
            },
            ["cat_scratch0"] = new[]
            {
                "...K.K......",
                "..KWKWK.....",
                "..KWWWWK.KK.",
                "..KWWWWKKWWK",
                "..KWWWWWWKK.",
                "...KWWWWK...",
                "..KWWWWWKKK.",
                "..KWWWWWWWWK",
                ".KKWWWWWWKK.",
                "KWKWgWWWK...",
                "KWKWWWWWK...",
                "KWKWKKKWK...",
                ".KKKK.KKK...",
            },
            ["cat_scratch1"] = new[]
            {
                "...K.K......",
                "..KWKWK.....",
                "..KWWWWK....",
                "..KWWWWKKKK.",
                "..KWWWWWWWWK",
                "...KWWWWKKK.",
                "..KWWWWWK.KK",
                "..KWWWWWKKWK",
                ".KKWWWWWWKK.",
                "KWKWgWWWK...",
                "KWKWWWWWK...",
                "KWKWKKKWK...",
                ".KKKK.KKK...",
            },
            ["cat_stretch"] = new[]
            {
                ".KK..............",
                "KWWK.............",
                "KWKKKK........K.K",
                ".KWWWWKK....KWKWK",
                ".KWWWWWWKK..KWWWK",
                ".KWWKKWWWWKKKWWWK",
                "..KWK.KWWWWWWWWK.",
                "..KWK..KKKKWWWK..",
                "..KKK...KKKKKKK..",
            },
            ["cat_jump"] = new[]
            {
                "..........K..K.",
                "KK.......KWKKWK",
                ".KKKKKKKKWWWWWK",
                "..KWWWWWWWWWWWK",
                ".KWKKWWWWWWKWK.",
                "KK...KKKKKKK...",
            },

            // ---- Icons (8x8). Grey-scale ones are tinted per item. ------------------
            // Three peppercorns; grey bodies with a highlight so they read on both parchment and the dark HUD.
            ["ic_peppercorn"] = new[]
            {
                "........",
                "..KK.KK.",
                ".KgGKgGK",
                ".KGGKGGK",
                "..KK.KK.",
                ".KK.KK..",
                "KgGKgGK.",
                ".KK.KK..",
            },
            ["ic_seed"] = new[]
            {
                "WWWWWWW.",
                "WggggggW",
                "WgGGGGgW",
                "WgGKKGgW",
                "WgGKKGgW",
                "WgGGGGgW",
                "WggggggW",
                ".WWWWWWW",
            },
            ["ic_bell"] = new[]
            {
                "...LL...",
                "...YY...",
                "..ZyYY..",
                "..ZyYY..",
                ".ZyyYYY.",
                ".YYYYYY.",
                "OOOOOOOO",
                "...K....",
            },
            ["ic_banana"] = new[]
            {
                "......d.",
                ".....yy.",
                "....Zyy.",
                "...Zyy..",
                "..Zyy...",
                ".yyy....",
                "Yyy.....",
                ".Y......",
            },
            ["ic_bonnet"] = new[]
            {
                "..oooo..",
                ".oZooOo.",
                "oooooooi",
                "OoooooOi",
                "wWwWwWwi",
                ".wwwwww.",
                "........",
                "........",
            },
            ["ic_ghost"] = new[]
            {
                "..L.....",
                ".tttt...",
                "tKttKt..",
                "tttttT..",
                "tttttTT.",
                ".ttttTT.",
                "..tTtT..",
                "...T.t..",
            },
            ["ic_powder"] = new[]
            {
                "........",
                "........",
                "....W...",
                "...WWW..",
                "..WWWWg.",
                ".WWWWggg",
                "WWWWgggG",
                "GGGGGGGG",
            },
            ["ic_mash"] = new[]
            {
                ".KKKKKK.",
                ".KGGGGK.",
                "gggggggg",
                "gWWWWWWg",
                "gWWWWWWg",
                "gWWWWWWg",
                "gWWWWWWg",
                ".gggggg.",
            },
            ["ic_pouch"] = new[]
            {
                "...KK...",
                "..K..K..",
                "...KK...",
                "..WWWW..",
                ".WWWWWW.",
                ".WWWgWW.",
                ".WWgggW.",
                "..gggg..",
            },
            ["ic_hot"] = new[]
            {
                "...KK...",
                "...KK...",
                "..gggg..",
                ".gWWWWg.",
                ".gWWWWg.",
                ".gWWWWg.",
                ".gWWWWg.",
                "..gggg..",
            },
            ["ic_curry"] = new[]
            {
                "........",
                "........",
                "KKKKKKKK",
                ".WWWWWW.",
                ".WWWWWW.",
                "..gggg..",
                "...gg...",
                "..GGGG..",
            },
            ["ic_blend"] = new[]
            {
                ".KKKKKK.",
                ".KgKgKg.",
                ".KKKKKK.",
                ".WWWWWW.",
                ".WWggWW.",
                ".WgWWgW.",
                ".WWggWW.",
                ".gggggg.",
            },
            ["ic_water"] = new[]
            {
                "...c....",
                "...c....",
                "..jcc...",
                "..jcc...",
                ".jjccC..",
                ".jccCC..",
                ".cCCCC..",
                "..CCC...",
            },
            ["ic_flame"] = new[]
            {
                "...r....",
                "...rr...",
                "..rro...",
                "..rooo..",
                ".rooyor.",
                ".royZor.",
                ".rooyor.",
                "..rrrr..",
            },
            ["ic_star"] = new[]
            {
                "...y....",
                "...y....",
                "..yZy...",
                "yyyZyyy.",
                ".yyZyy..",
                "..yyy...",
                ".yy.yy..",
                "y.....y.",
            },
            ["ic_star_dim"] = new[]
            {
                "...G....",
                "...G....",
                "..GGG...",
                "GGGGGGG.",
                ".GGGGG..",
                "..GGG...",
                ".GG.GG..",
                "G.....G.",
            },
            ["ic_hat"] = new[]
            {
                "...PP...",
                "...pP...",
                "..ppPP..",
                "..pPPP..",
                ".ppPPPv.",
                ".pPPPPv.",
                "YyyyyyYY",
                "........",
            },
            ["ic_lock"] = new[]
            {
                "..KKKK..",
                ".K....K.",
                ".K....K.",
                "KKKKKKKK",
                "KyyyyyyK",
                "KyyKyyyK",
                "KyyyyyyK",
                "KKKKKKKK",
            },

            ["ic_sun"] = new[]
            {
                "........",
                ".y.yy.y.",
                "..yZZy..",
                ".yZZZZy.",
                ".yZZZZy.",
                "..yZZy..",
                ".y.yy.y.",
                "........",
            },
            ["ic_envelope"] = new[]
            {
                "........",
                "KKKKKKKK",
                "KwwwwwwK",
                "KKwwwwKK",
                "KwKwwKwK",
                "KwwKKwwK",
                "KwwwwwwK",
                "KKKKKKKK",
            },
            ["ic_moon"] = new[]
            {
                "....KK....",
                "...KWWK...",
                "..KWWK....",
                ".KWWK...K.",
                ".KWWK..KWK",
                ".KWWwKKWwK",
                "..KWWwwwK.",
                "...KKKKK..",
            },
            ["ic_rain"] = new[]
            {
                "..gWWg..",
                ".gWWWWg.",
                "gWWWWWWg",
                ".GGGGGG.",
                "..c..c..",
                ".c..c..c",
                "..c..c..",
                ".c..c...",
            },
            ["ic_wind"] = new[]
            {
                "........",
                "..WWWg..",
                ".W....g.",
                "WWWWWg..",
                "........",
                "..WWWWWg",
                ".W....Wg",
                "WWWWWg..",
            },
            // Bobs over anything that wants clicking: a ripe plot, a ready jar, sauces waiting to ship.
            ["ic_bang"] = new[]
            {
                ".KKK.",
                ".KZK.",
                ".KyK.",
                ".KyK.",
                ".KKK.",
                ".KZK.",
                ".KKK.",
            },
            ["ic_check"] = new[]
            {
                "........",
                ".......l",
                "......ll",
                ".....ll.",
                "l...ll..",
                "ll.ll...",
                ".lll....",
                "..l.....",
            },
            ["ic_cross"] = new[]
            {
                "........",
                ".G....G.",
                ".GG..GG.",
                "..GGGG..",
                "...GG...",
                "..GGGG..",
                ".GG..GG.",
                ".G....G.",
            },

            // ---- UI chrome: 9-slice frames (each 3x3 cells of 4px) ----------------------
            // Bevelled oak frame around parchment.
            ["frame"] = new[]
            {
                "KKKKKKKKKKKK",
                "KNNNNNNNNNBK",
                "KNbbbbbbbbBK",
                "KNbKKKKKKdBK",
                "KNbKwwwwKdBK",
                "KNbKwwwwKdBK",
                "KNbKwwwwKdBK",
                "KNbKwwwwKdBK",
                "KNbKKKKKKdBK",
                "KNbddddddddK",
                "KBBBBBBBBBBK",
                "KKKKKKKKKKKK",
            },
            ["button"] = new[]
            {
                ".KKKKKKKKKK.",
                "KZZZZZZZZZZK",
                "KZyyyyyyyyYK",
                "KZyyyyyyyyYK",
                "KZyyyyyyyyYK",
                "KZyyyyyyyyYK",
                "KZyyyyyyyyYK",
                "KZyyyyyyyyYK",
                "KZyyyyyyyyYK",
                "KZyyyyyyyyYK",
                "KYYYYYYYYYYK",
                ".KKKKKKKKKK.",
            },
            ["button_dim"] = new[]
            {
                ".KKKKKKKKKK.",
                "KggggggggggK",
                "KgGGGGGGGGGK",
                "KgGGGGGGGGGK",
                "KgGGGGGGGGGK",
                "KgGGGGGGGGGK",
                "KgGGGGGGGGGK",
                "KgGGGGGGGGGK",
                "KgGGGGGGGGGK",
                "KgGGGGGGGGGK",
                "KGGGGGGGGGGK",
                ".KKKKKKKKKK.",
            },
        };
    }
}
